/*
2020 AMC 12B Problem 15
There are 10 people standing equally spaced around a circle. 
Each person knows exactly 3 of the other 9 people: 
the 2 people standing next to her or him, 
as well as the person directly across the circle. 
How many ways are there for the 10 people to split up into 5 pairs 
so that the members of each pair know each other?

(A) 11   (B) 12   (C)   13    (D)   14   (E) 15
*/